/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from "react";

import { Float, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Vector3 } from "three";
import type { GLTF } from "three-stdlib";

import { useDebug } from "~/components/canvas/Debug";
import useMousePos from "~/hooks/useMousePos";
import useViewport from "~/hooks/useViewport";

const lookTo = new Vector3();
const lerpTo = new Vector3();

export default function Mouse({
  cableRef,
  ...props
}: {
  cableRef: React.RefObject<THREE.Mesh>;
} & JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/mouse.gltf") as GLTFResult;
  const mouseRef = useRef<THREE.Group>(null);
  const { width, height, mobile } = useViewport();
  const {
    relative: { x, y },
  } = useMousePos();
  const debug = useDebug();

  useFrame((_, delta) => {
    if (mobile) return null;

    mouseRef.current?.lookAt(
      lookTo.lerp(lerpTo.set(x, -y - 2.5, 3.5), delta * 8)
    );
  });

  return (
    <Float speed={3} rotationIntensity={0.5} floatIntensity={0.5}>
      <group
        ref={mouseRef}
        dispose={null}
        scale={mobile ? width * 0.3 : 1.5}
        position={
          mobile ? [0, -height * 0.2, -0.5] : [width * 0.2, -height * 0.2, -0.5]
        }
        rotation={
          mobile ? [Math.PI * 0.15, 0, 0] : [Math.PI * 0.15, -Math.PI * 0.1, 0]
        }
        {...props}
        {...debug}
      >
        <mesh
          position={[-0.1, 0.25, 0.55]}
          ref={cableRef}
        />
        <group position={[-0.1, 0.14, 0.95]} rotation={[3.124, 0.03, -3.141]}>
          <mesh
            geometry={nodes.Plane.geometry}
            material={materials["matt plastic grey"]}
          />
          <mesh
            geometry={nodes.Plane_1.geometry}
            material={materials["matt plastic black"]}
          />
          <mesh
            geometry={nodes.Plane_2.geometry}
            material={materials["glossy plastic black"]}
          />
          <mesh geometry={nodes.Plane_3.geometry} material={materials.led} />
        </group>
      </group>
    </Float>
  );
}

type GLTFResult = GLTF & {
  nodes: {
    Keyboard_cable: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane_3: THREE.Mesh;
  };
  materials: {
    ["Black rubber"]: THREE.MeshStandardMaterial;
    ["matt plastic grey"]: THREE.MeshStandardMaterial;
    ["matt plastic black"]: THREE.MeshStandardMaterial;
    ["glossy plastic black"]: THREE.MeshStandardMaterial;
    led: THREE.MeshStandardMaterial;
  };
};

useGLTF.preload("/mouse.gltf");
